# Set Craft & Public folder permissions

# NB This (deliberately) means we can't run local updates!  Must run and test updates on dev then push out to the server!
- name: "Set Craft folder & file permissions to u+rwX"
  file: 
    path: "{{ release_craft_folder }}" 
    mode: u=rwX
    recurse: yes

# NB if you are using any local asset sources, this would need to be group writeable in addition.
# But all my assets sources are on S3
- name: "Set Public folder & file permissions to -> u=rwX,g=rX,o=rX"
  file:
    path: "{{ release_public_folder }}"
    mode: u=rwX,g=rX,o=rX
    recurse: yes


# Server Configuration Changes

# Upload our custom .conf for apache
- name: Copy apache-{{easy_name}}.conf to server & put zzz in front of it to make sure it's the last loaded conf
  template: 
    src: "../files/configuration/apache-{{easy_name}}.conf"
    dest: "/etc/apache-sp/vhosts.d/{{sp_appname}}.d/zzz_apache-{{easy_name}}.conf"
  become: yes
  become_user: root
  register: apachesp

# Upload our custom .conf for php
- name: Copy php-{{easy_name}}.conf
  template: 
    src: "../files/configuration/php-{{easy_name}}.conf"
    dest: "/etc/php7.0-sp/fpm-pools.d/{{sp_appname}}.d/"
  become: yes
  become_user: root
  register: phpfpmsp

# Production is no longer behind a password....
# Upload .htpasswd
- name: Copy htpasswd
  template: 
    src: ../files/credentials/htpasswd-{{easy_name}} 
    dest: "{{ release_public_folder }}"
  when: "'production' not in group_names"
# Symlink .htpasswd to the uploaded file
- name: Link .htpasswd
  file: 
    src: "{{release_public_folder }}/htpasswd-{{easy_name}}"
    dest: "{{ release_public_folder }}/.htpasswd"
    state: link
  when: "'production' not in group_names"

# SWITCH IN THE RELEASE
#######################

# Re-point symlinks to this new release
- name: "Update craft symlink to point to latest release"
  file: 
    src: "{{ release_craft_folder }}"
    dest: "{{ craft_dir }}"
    state: link

- name: "Update public symlink to point to latest release"  
  file: 
    src: "{{ release_public_folder }}"
    dest: "{{ public_dir }}"
    state: link
  
# PRODUCTION ONLY PLUGINS NEED TO BE LINKED IN
###############################################
- name: Link Rollbar plugin only in production
  file: 
    src: "{{craft_dir}}/production-only-plugins/rollbar"
    dest: "{{craft_dir}}/plugins/rollbar"
    state: link
  when: "'production' in group_names"



