

# Optionally import the DB automatically 
# two different methods depending on whether it's coming from a quick and dirty deploy-local
# or a proper timestamp/git release
# On Production we probably won't do this...

- name: "Import database on server"
  mysql_db: name=craft_projectname state=import target="{{ release_folder }}/craft.sql"
  when: deploy_local_db is defined and import_db is defined

# - name: "Import database on server (db from git repo)"
#   mysql_db: name=craft_projectname state=import target="{{ release_folder }}/dbdump/craft.sql"
#   when: deploy_repo_db is defined and import_db is defined

# Set folder permissions
- name: "Set Craft folder permissions"
  file: path="{{ release_craft_folder }}/app" mode=0744
  file: path="{{ release_craft_folder }}/config" mode=0744
  file: path="{{ release_craft_folder }}/storage" mode=0744


# CONFIGURE THE NEW PUBLIC FOLDER
#############################

# Upload .htaccess
- name: Copy .htaccess-staging
  copy: src=htaccess/htaccess-staging dest={{ release_public_folder }}

# Symlink .htaccess to the uploaded file
- name: Link .htaccess to .htaccess-staging 
  file: src={{release_public_folder }}/htaccess-staging dest={{ release_public_folder }}/.htaccess state=link

# Upload .htpasswd
- name: Copy htpasswd-staging
  copy: src=credentials/htpasswd-staging dest={{ release_public_folder }}

# Symlink .htpasswd to the uploaded file
- name: Link .htpasswd to .htpasswd-staging 
  file: src={{release_public_folder }}/htpasswd-staging dest={{ release_public_folder }}/.htpasswd state=link


# SWITCH IN THE RELEASE
#######################

# Re-point symlinks to this new release
- name: "Update craft symlink to point to latest release"
  file: src={{ release_craft_folder }} dest={{ craft_dir }} state=link
- name: "Update public symlink to point to latest release"  
  file: src={{ release_public_folder }} dest={{ public_dir }} state=link
  




