# Set folder permissions
- name: "Set Craft app folder permissions"
  file: path="{{ release_craft_folder }}/app" mode=0744
- name: "Set Craft config folder permissions"  
  file: path="{{ release_craft_folder }}/config" mode=0744
- name: "Set Craft storage folder permissions"  
  file: path="{{ release_craft_folder }}/storage" mode=0744


# CONFIGURE THE NEW PUBLIC FOLDER
#############################

# Upload our custom .conf we use instead of .htaccess
- name: Copy z_appname.conf
  copy: src=conf/z_appname-{{easy_name}}.conf dest=/etc/apache-sp/vhosts.d/appname.d/
  become: yes
  become_user: root

# @TODO - stop this happening when host is production, as not needed
# Upload .htpasswd
- name: Copy htpasswd
  copy: src=credentials/htpasswd-{{easy_name}} dest={{ release_public_folder }}

# Symlink .htpasswd to the uploaded file
- name: Link .htpasswd
  file: src={{release_public_folder }}/htpasswd-{{easy_name}} dest={{ release_public_folder }}/.htpasswd state=link


# SWITCH IN THE RELEASE
#######################

# Re-point symlinks to this new release
- name: "Update craft symlink to point to latest release"
  file: src={{ release_craft_folder }} dest={{ craft_dir }} state=link
- name: "Update public symlink to point to latest release"  
  file: src={{ release_public_folder }} dest={{ public_dir }} state=link
  




