---

# COMPILE JS/CSS FROM SRC
#########################

- name: "Update nodejs to latest"
  apt: 
    name: nodejs 
    state: latest
  
- name: "Update npm to latest"
  npm: 
    name: npm 
    state: latest 
    global: true
  become: yes
  become_user: root
  
# Update node packages
- name: "Update node packages"
  npm: 
    path: "{{ release_folder }}"
    state: latest

# Install local gulp
- name: Install (local) Gulp package
  npm: 
   name: gulp
   state: present
   version: latest
   path: "{{ release_folder }}"
  tags: gulp

# Compile with gulp.
- name: "Compile the release with Gulp"
  command: gulp production chdir="{{ release_folder }}"

