---

############# NOTE EXCLUSIONS MUST USE THE SERVER SIDE PATH BELOW!!!


# Deploys your current codebase to a server

# Set Release Folder - 'dev' - to indicate this is current development code
- include_tasks: ../../create-release-folders/tasks/create-release-folders.yaml 
  vars:
    folder: dev
        

# This is quick and dirty - just rsync up all the compiled code...
- name: Push current `craft` to server
  synchronize: 
    mode: push 
    delete: yes 
    recursive: yes 
    src: "../../craft"
    dest: "{{ release_folder }}"
    rsync_opts:
        - "--exclude=craft/storage/runtime"
        - "--exclude=craft/storage/backups"

- name: Push current `public_html` to server
  synchronize: 
    mode: push 
    delete: yes 
    recursive: yes 
    src: "../../public_html"
    dest: "{{ release_folder }}"
    rsync_opts: 
        - "--exclude=public_html/_your_imager-transforms-folder"

  