# Install Amazon AWS CLI python package.
- name: PIP Install the Amazon AWS Tools
  pip: name=awscli

# Needed to make bash scripts unix friendly...
- name: Install dos2unix because we live in 1976 apparently
  apt: pkg=dos2unix state=latest
  become: yes
  become_user: root

# AWS Setup
- name: Create AWS config directory
  file: path={{ home_dir }}/.aws state=directory
- name: Copy AWS credentials
  copy: src=credentials/aws-credentials dest={{ home_dir }}/.aws/credentials
- name: Copy AWS configuration
  copy: src=config/aws-config dest={{ home_dir }}/.aws/config

# DB Backups
- name: Create script directory
  file: path={{ home_dir }}/scripts state=directory
- name: Create backups directory
  file: path={{ home_dir }}/backups state=directory
# Grab backup script
- name: Copy backup script
  copy: src=scripts/backup-to-s3.sh dest={{ home_dir }}/scripts

- name: Fix windows/unix crlf shite
  shell: dos2unix {{ home_dir }}/scripts/backup-to-s3.sh

- name: Chmod +x db backup script
  file: path={{ home_dir }}/scripts/backup-to-s3.sh mode="a+x"
- name: Set up an hourly cron for backup (backups are run as root)
  cron: name="Backup DB to S3" minute=0 job="/srv/users/serverpilot/scripts/backup-to-s3.sh > /dev/null 2>&1"
  become: yes
  become_user: root

