---
# This is basically a one off preparatory playbook that gets the basics in place before any deployment is done
# (You can run this whenever you like of course).

- name: Update apt cache
  apt: update_cache=yes
  become: yes
  become_user: root
  ignore_errors: true
  
- name: Create releases directory under app
  file: path={{ releases_dir }} state=directory

# Grab staging .my.cnf from the repo and upload it
- name: Copy .my.cnf
  copy: src=credentials/my.cnf-{{easy_name}} dest={{ home_dir }}/.my.cnf

- name: Set up a cron to keep mysql optimised
  cron: name="Mysqlcheck optimise" minute="33" hour="4" job="mysqlcheck -o --all-databases > /dev/null 2>&1"
  become: yes
  become_user: root
  
- name: Copy html5 boilerplate conf
  copy: src=conf/html5_boilerplate.conf dest=/etc/apache-sp/conf.d/
  become: yes
  become_user: root
  
- name: Copy mysql.cnf to fix Craft issues with MYSQL 5.7+
  copy: src=conf/my.cnf dest=/etc/mysql/
  become: yes
  become_user: root

- name: Install optipng
  apt: pkg=optipng state=latest
  become: yes
  become_user: root

- name: Install jpegoptim
  apt: pkg=jpegoptim state=latest
  become: yes
  become_user: root  

- name: Copy .bashrc for user servpilot
  copy: src=conf/.bashrc dest={{ home_dir }}/.bashrc

- name: Copy .bashrc for user root
  copy: src=conf/.bashrc dest=/root/.bashrc
  become: yes
  become_user: root 

