
# Record folders for later use
- name: Register release folder
  set_fact:
    release_folder: "{{app_dir}}/releases/{{folder}}"

- name: Register release craft folder
  set_fact:    
    release_craft_folder: "{{release_folder}}/craft"

- name: Register release public folder
  set_fact: 
    release_public_folder: "{{release_folder}}/public_html"

# Create release directory
- name: Create release directory
  file: path={{release_folder}} state=directory

# @TODO - this should not happen/be here as it defeats the purpose of swapping in releases...
# I think this was only here as part of new sevrer setup stuff...so should be moved there maybe?
# Unlink public (or remove the original ServerPilot one) as we're going to swap in our new release link
#- name: Remove the default ServerPilot public folder so we can link in our release folder later
#  file: path=/srv/users/serverpilot/apps/appname/public state=absent
  