---

releases_to_keep: "3"
build_repo_src: "git@bitbucket.org:/username/projectname.git"

home_dir: "/srv/users/serverpilot"
app_dir: "/srv/users/serverpilot/apps/projectname"
# these are what get symlinked to the actual release files....
craft_dir: "{{ app_dir }}/craft"
public_dir: "{{ app_dir }}/public"
# ....that live under here
releases_dir: "{{ app_dir }}/releases"


